require('config.keymaps.code-edit-mappings')
require('config.keymaps.code-clean-mappings')
require('config.keymaps.buffer-mappings')
require('config.keymaps.telescope-mappings')
require('config.keymaps.other-mappings')
require('config.keymaps.personal-mappings')
require('config.keymaps.git-mappings')
require('config.keymaps.gp-mappings')
